Tracker:AddLocations("locations/worldmap.jsonc")
-- South
Tracker:AddLocations("locations/south/startcamp.jsonc")
Tracker:AddLocations("locations/south/swamp.jsonc")
Tracker:AddLocations("locations/south/junkyard_area.jsonc")
Tracker:AddLocations("locations/south/junkyard_shed.jsonc")
Tracker:AddLocations("locations/south/south_house.jsonc")
Tracker:AddLocations("locations/south/military_base.jsonc")
Tracker:AddLocations("locations/south/south_mine.jsonc")
-- Central
Tracker:AddLocations("locations/central/middle_station.jsonc")
Tracker:AddLocations("locations/central/canyon.jsonc")
Tracker:AddLocations("locations/central/watchtower.jsonc")
Tracker:AddLocations("locations/central/boulder_field.jsonc")
Tracker:AddLocations("locations/central/haunted_house.jsonc")
Tracker:AddLocations("locations/central/santiago_house.jsonc")
Tracker:AddLocations("locations/central/port.jsonc")