Tracker:AddLocations("locations/worldmap.jsonc")

-- South
Tracker:AddLocations("locations/south/startcamp.jsonc")
Tracker:AddLocations("locations/south/swamp.jsonc")
Tracker:AddLocations("locations/south/junkyard_area.jsonc")
Tracker:AddLocations("locations/south/junkyard_shed.jsonc")
Tracker:AddLocations("locations/south/south_house.jsonc")
Tracker:AddLocations("locations/south/military_base.jsonc")
Tracker:AddLocations("locations/south/south_mine.jsonc")

-- Central
Tracker:AddLocations("locations/central/middle_station.jsonc")
Tracker:AddLocations("locations/central/canyon.jsonc")
Tracker:AddLocations("locations/central/watchtower.jsonc")
Tracker:AddLocations("locations/central/boulder_field.jsonc")
Tracker:AddLocations("locations/central/haunted_house.jsonc")
Tracker:AddLocations("locations/central/santiago_house.jsonc")
Tracker:AddLocations("locations/central/port.jsonc")
Tracker:AddLocations("locations/central/lost_stairs.jsonc")
Tracker:AddLocations("locations/central/shrine.jsonc")
Tracker:AddLocations("locations/central/temple.jsonc")
Tracker:AddLocations("locations/central/pickle_val.jsonc")

-- East
Tracker:AddLocations("locations/east/trench_house.jsonc")
Tracker:AddLocations("locations/east/doll_house.jsonc")
Tracker:AddLocations("locations/east/lighthouse.jsonc")
Tracker:AddLocations("locations/east/east_tower.jsonc")
Tracker:AddLocations("locations/east/rocket_grounds.jsonc")
Tracker:AddLocations("locations/east/workshop.jsonc")

-- North
Tracker:AddLocations("locations/north/barbed_shelter.jsonc")
Tracker:AddLocations("locations/north/caravan.jsonc")
Tracker:AddLocations("locations/north/church.jsonc")
Tracker:AddLocations("locations/north/mine_elevator_exit.jsonc")
Tracker:AddLocations("locations/north/mine_shaft.jsonc")
Tracker:AddLocations("locations/north/mob_camp.jsonc")
Tracker:AddLocations("locations/north/morse_bunker.jsonc")
Tracker:AddLocations("locations/north/mountain_ruin.jsonc")
Tracker:AddLocations("locations/north/museum.jsonc")
Tracker:AddLocations("locations/north/north_beach.jsonc")
Tracker:AddLocations("locations/north/north_mine.jsonc")
Tracker:AddLocations("locations/north/towers.jsonc")
Tracker:AddLocations("locations/north/trailer_cabin.jsonc")
Tracker:AddLocations("locations/north/west_beach.jsonc")
Tracker:AddLocations("locations/north/west_cottage.jsonc")
Tracker:AddLocations("locations/north/wood_bridge.jsonc")